version: "3.7"
networks:
  booking-beacon-network:
    driver: bridge

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    restart: always