# application.yml
server:
  port: 8080

spring:
  application:
    name: booking-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Dr8i3ubMyCt8WNc/SpPreDQtCbrQYZkx+3MuWh6JktBvJXQBXp3h16P4CBfJ4Ja97mzCs6BhvBgTWvJRO18kGIZFbe+7UcG5v00ZQkyuA77iPPaL1P9rtg==)
    username: root
    password: ENC(auQgF7+6yjdXi19x2QgpyS3XWmN+e2CH)
#  kafka:
#    admin:
#      auto-create: true
#    bootstrap-servers: localhost:9092
  data:
    redis:
      host: ENC(S9GOFqVPSNMM9bQKwGKrmb5l3be/4inRe6ppgMr5mIETVGnn5ydVfKdGZqSnIKlXkyaNXkEwuESWFy/v+WJygn+pwzv4d+I5qaW8mtX5Va4=)
      port: 6379
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    username: ENC(WbmFP7v16wJ24QfMRhhjm9ajkQForg77RU+xm2nFs9Xb6OIG/qfQPQ==)
    password: ENC(14KpaE20aWlGCEPWL7caEzi/G0gB+NM6xkMNDerAzTU=)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: ENC(J75n9EXpmHVC4t/vYOHbORr73x394E69sYd7axyU/oMcDq6vP2s9FZ+utIKSEfusPbfOfz7sKcZk5jFgRyQ1d40mIGz64g5AGBDdQtnGeiM=)
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 86400

cloud:
  aws:
    s3:
      bucket: booking-beacon-s3-dev
      accessKey: ENC(h2frLs6THDKN+1dJRlvcTjwtZyrREYNxRB+L7isu/Hc=)
      secretKey: ENC(RiNrOIfArFNNMMPO9e5ArdaFDmT7NGTo+NRGpLnT1a/Le2XpKaHu/JAzsWyeUON38rtdQQZiSc8=)
      stack:
        auto: false
      region: ap-northeast-2

springdoc:
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    default-model-expand-depth: 3
    default-models-expand-depth: 3
    path: /swagger
  api-docs:
    enabled: true
    path: /api-docs
  cache:
    disabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
